version: '3.2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'pedidos'
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    #volumes:
     # - ../docker-volumes/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    #volumes:
    #  - ./volumes/pgadmin:/root/.pgadmin
    ports:
      - "4444:80"